# Generated by Django 4.2.3 on 2023-07-17 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(44), django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('bordado_nombre', models.CharField(max_length=64)),
                ('celular', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)])),
                ('total', models.IntegerField()),
                ('a_cuenta', models.IntegerField()),
                ('resta', models.IntegerField()),
                ('chamarra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes.tallas')),
                ('chamarra_cantidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes.cantidad')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes.escuela')),
            ],
        ),
    ]
