# Generated by Django 4.2.3 on 2023-07-18 00:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tallas_chamarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(44), django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='cantidad',
            name='cantidad',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='bordado_nombre',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='chamarra_cantidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uniformes.cantidad'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='chamarra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uniformes.tallas_chamarra'),
        ),
        migrations.DeleteModel(
            name='Tallas',
        ),
    ]
