# Generated by Django 4.2.3 on 2023-07-18 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0002_tallas_chamarra_remove_pedidos_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidad',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='bordado_nombre',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='chamarra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='uniformes.tallas_chamarra'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='chamarra_cantidad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='uniformes.cantidad'),
        ),
        migrations.AlterField(
            model_name='tallas_chamarra',
            name='talla',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(44), django.core.validators.MinValueValidator(2)]),
        ),
    ]
