# Generated by Django 4.2.3 on 2023-07-18 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0003_alter_cantidad_cantidad_alter_pedidos_bordado_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidad',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='tallas_chamarra',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='tallas_chamarra',
            name='talla',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(44), django.core.validators.MinValueValidator(0)]),
        ),
    ]
