# Generated by Django 4.2.3 on 2023-07-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0010_alter_pedidos_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_hora',
            field=models.CharField(default='2023-07-26 22:25:20', max_length=64),
        ),
    ]
