# Generated by Django 4.2.3 on 2023-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0011_alter_pedidos_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='total',
            name='id',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='pedido',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_hora',
            field=models.CharField(default='2023-07-30 23:26:11', max_length=64),
        ),
        migrations.AlterField(
            model_name='resta',
            name='pedido',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='total',
            name='pedido',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
