# Generated by Django 4.2.3 on 2023-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0012_remove_cuenta_id_remove_resta_id_remove_total_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Resta',
        ),
        migrations.AddField(
            model_name='total',
            name='a_cuenta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='total',
            name='entregado',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AddField(
            model_name='total',
            name='resta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_hora',
            field=models.CharField(default='2023-07-31 16:23:35', max_length=64),
        ),
        migrations.AlterField(
            model_name='total',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
